apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: ClusterIP
  selector:
    app: 
  ports:
    - name: http
      port: 80
      targetPort: 80
  #   protocol: TCP  # optional protocol
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: Deny";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      more_set_headers "X-Content-Type-Options: nosniff";
  name: 
  namespace: default
spec:
  rules:
    - host: 
      http:
        paths:
        - backend:
            service:
              name: 
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific